### ISSUE TITLE
not compatible with current simplesamlphp master branch

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp-module-radius#3]
Neither v1.0.1 nor master of this module work with the current master branch of simplesamlphp itself (upcoming 2.0). The exception that is thrown is:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
1 /export/hosting/restena/clueless_private/htdocs/simplesaml-master-80/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Could not resolve 'radius:Radius': The class 'SimpleSAML\Module\radius\Auth\Source\Radius' isn't a subclass of '\SimpleSAML\Auth\Source'.
Backtrace:
5 lib/SimpleSAML/Module.php:434 (SimpleSAML\Module::resolveClass)
4 lib/SimpleSAML/Auth/Source.php:314 (SimpleSAML\Auth\Source::parseAuthSource)
3 lib/SimpleSAML/Auth/Source.php:357 (SimpleSAML\Auth\Source::getById)
2 lib/SimpleSAML/IdP.php:105 (SimpleSAML\IdP::__construct)
1 lib/SimpleSAML/IdP.php:137 (SimpleSAML\IdP::getById)
0 /export/hosting/restena/clueless_private/htdocs/simplesaml-1.19.0/saml2/idp/SSOService.php:23 (N/A)

Looks like something about class structuring changed.

**Comment by tvdijen** [comment]
Hi @restena-sw !  In SSP 2.0 (dev-master) modules have to be specifcally enabled in config.php.. Could that be the issue here?

**Comment by restena-sw** [comment]
Ah! The config talks about an "override" still and I thought the mere presence of a module is enough to make it enabled (as opposed to default-enable/default-disable times).

Now I've enabled the module explicitly in config, and it works. Thanks!

**Comment by tvdijen** [comment]
Thanks for pointing that out.. I'll try and clarify the text in the config template

**Comment by thijskh** [comment]
Can we improve the exception text?

**Comment by tvdijen** [comment]
I just did;  a6b266940bf510bd6b61d9b58a3619c0f976f247
